# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 995ce245b18cea22f56437426d08a1926c3f1e33e123b7843b5b306ed4db43a5fa1f6892bd6822110661b480ac18ad9b2e0adc787872b7882593c390f650f73f

test:
  secret_key_base: 947d1eab1a164d1095eac0ffb01656215651a0d2b9097983b42d02fa9e314f2a7c43c590eb27dba3cd0f581468fae2e259e2039475ceea5597f5dc4e925e5398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
